States Incentives and Regulations, Adding and Clicking Hover Feature
mcsc-impact-climate/FAF5-Analysis pull request #10
Opened 2024-08-15 17:30 UTC by brookebao

2024-08-15 19:13 UTC, danikam requested changes
Amazing work @brookebao, thanks for your awesome contributions to the tool!! 🚀 

I've tested the functionality and it works perfectly from my side. 

Just had some very minor comments and suggestions in the code review. Please take a look and let me know once they've been incorporated and I'll merged in the PR.

2024-08-15 19:13 UTC, danikam commented on web/static/.Rhistory
Hey @brookebao, it looks like there's a new file called .Rhistory - just checking if it's needed?

2024-08-15 19:13 UTC, danikam commented on web/static/name_maps.js
> +  'DOE Corridors': ['point', 'other'],
I think it might make sense to comment this out for now since the DOE corridor effort got put on pause.

2024-08-15 19:13 UTC, danikam commented on web/static/name_maps.js
> +  'DOE corridors': "Locations of truck stops parking facilities in the U.S. Obtained from the DOT Bureau of Transportation Statistics's <a href='https://geodata.bts.gov/datasets/usdot::truck-stop-par
Same here, probably should comment this out for now.

2024-08-19 15:19 UTC, brookebao commented on web/static/.Rhistory
I don't remember creating it...so probably not. I also don't see it in my files locally

2024-08-19 16:14 UTC, danikam commented on web/static/.Rhistory
Ok, thanks! I'll delete it then.

2024-08-19 16:15 UTC, danikam commented
Merging this PR. Thanks @brookebao for your awesome work and iteration on it!

2024-08-19 16:15 UTC, merged